# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/126KtB0DyiTuvFf2ZkXF45vctQKxXvwEg
"""

!pip install -q youtube-transcript-api yt-dlp openai-whisper
!apt-get install -y ffmpeg > /dev/null 2>&1

"""
YouTube Transcript Extraction System with Whisper Fallback
GOOGLE COLAB VERSION - Ready to run in Colab notebook
"""

# ============================================================================
# STEP 1: INSTALL DEPENDENCIES (Run this cell first)
# ============================================================================

"""
!pip install -q youtube-transcript-api
!pip install -q yt-dlp
!pip install -q openai-whisper
!apt-get install -y ffmpeg > /dev/null 2>&1
"""


# ============================================================================
# STEP 2: IMPORT LIBRARIES AND CONFIGURATION
# ============================================================================

import os
import re
import tempfile
from typing import Dict, Optional
from youtube_transcript_api import YouTubeTranscriptApi
from youtube_transcript_api._errors import TranscriptsDisabled, NoTranscriptFound
import yt_dlp
import whisper
import torch

# Configuration
WHISPER_MODEL = "base"  # Options: tiny, base, small, medium, large
AUDIO_FORMAT = "mp3"
TEMP_DIR = "/content"  # Colab's temporary directory


# ============================================================================
# STEP 3: UTILITY FUNCTIONS
# ============================================================================

def get_video_id(url: str) -> Optional[str]:
    """Extract YouTube video ID from various URL formats."""
    try:
        patterns = [
            r'(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/)([a-zA-Z0-9_-]{11})',
            r'youtube\.com\/watch\?.*v=([a-zA-Z0-9_-]{11})'
        ]

        for pattern in patterns:
            match = re.search(pattern, url)
            if match:
                return match.group(1)

        if re.match(r'^[a-zA-Z0-9_-]{11}$', url):
            return url

        return None

    except Exception as e:
        print(f"❌ Error extracting video ID: {str(e)}")
        return None


def get_youtube_transcript(video_id: str) -> Optional[str]:
    """Fetch existing transcript/captions from YouTube."""
    try:
        transcript_list = YouTubeTranscriptApi.get_transcript(video_id)
        transcript_text = " ".join([entry['text'] for entry in transcript_list])

        print(f"✅ YouTube transcript found for video: {video_id}")
        return transcript_text

    except (TranscriptsDisabled, NoTranscriptFound) as e:
        print(f"ℹ️  No YouTube transcript available: {str(e)}")
        return None

    except Exception as e:
        print(f"❌ Error fetching transcript: {str(e)}")
        return None


def download_audio_from_youtube(url: str) -> Optional[str]:
    """Download audio from YouTube video using yt-dlp."""
    try:
        video_id = get_video_id(url)
        output_path = os.path.join(TEMP_DIR, f"yt_audio_{video_id}.{AUDIO_FORMAT}")

        ydl_opts = {
            'format': 'bestaudio/best',
            'postprocessors': [{
                'key': 'FFmpegExtractAudio',
                'preferredcodec': AUDIO_FORMAT,
                'preferredquality': '192',
            }],
            'outtmpl': output_path.replace(f'.{AUDIO_FORMAT}', ''),
            'quiet': True,
            'no_warnings': True,
        }

        print(f"⬇️  Downloading audio from YouTube...")
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            ydl.download([url])

        if os.path.exists(output_path):
            print(f"✅ Audio downloaded: {output_path}")
            return output_path
        else:
            print(f"❌ Audio file not found after download")
            return None

    except Exception as e:
        print(f"❌ Error downloading audio: {str(e)}")
        return None


def generate_transcript_from_audio(audio_path: str) -> Optional[str]:
    """Generate transcript from audio file using Whisper (local)."""
    try:
        # Check GPU availability (Colab provides free GPU)
        device = "cuda" if torch.cuda.is_available() else "cpu"
        print(f"🔧 Using device: {device.upper()}")

        if device == "cpu":
            print("⚠️  WARNING: Running on CPU. Enable GPU in Colab: Runtime > Change runtime type > GPU")

        # Load Whisper model
        print(f"⚙️  Loading Whisper model: {WHISPER_MODEL}")
        model = whisper.load_model(WHISPER_MODEL, device=device)

        # Transcribe audio
        print(f"🎤 Transcribing audio... (this may take a few minutes)")
        result = model.transcribe(audio_path, fp16=(device == "cuda"))

        transcript_text = result["text"].strip()
        print(f"✅ Transcription complete ({len(transcript_text)} characters)")

        return transcript_text

    except Exception as e:
        print(f"❌ Error during transcription: {str(e)}")
        return None


def cleanup_audio_file(audio_path: str) -> None:
    """Remove temporary audio file after processing."""
    try:
        if audio_path and os.path.exists(audio_path):
            os.remove(audio_path)
            print(f"🗑️  Cleaned up: {audio_path}")
    except Exception as e:
        print(f"⚠️  Warning: Could not delete {audio_path}: {str(e)}")


# ============================================================================
# STEP 4: MASTER FUNCTION
# ============================================================================

def fetch_final_transcript(youtube_url: str) -> Dict[str, Optional[str]]:
    """
    Master function to fetch transcript from YouTube (with Whisper fallback).

    Complete workflow:
    1. Extract video ID
    2. Try YouTube transcript API
    3. If unavailable, download audio with yt-dlp
    4. Transcribe with Whisper (GPU accelerated if available)
    5. Clean up temporary files
    6. Return transcript with metadata

    Args:
        youtube_url: YouTube video URL

    Returns:
        Dictionary containing:
        - transcript: Full transcript text
        - method_used: "youtube" or "whisper"
        - video_id: YouTube video ID
        - error: Error message if failed (None if successful)
    """
    result = {
        "transcript": None,
        "method_used": None,
        "video_id": None,
        "error": None
    }

    audio_path = None

    try:
        # Step 1: Extract video ID
        print(f"\n{'='*70}")
        print(f"🎬 Processing: {youtube_url}")
        print(f"{'='*70}\n")

        video_id = get_video_id(youtube_url)
        if not video_id:
            result["error"] = "Invalid YouTube URL"
            return result

        result["video_id"] = video_id

        # Step 2: Try YouTube transcript API first
        print("📝 Attempting to fetch YouTube transcript...")
        transcript = get_youtube_transcript(video_id)

        if transcript:
            result["transcript"] = transcript
            result["method_used"] = "youtube"
            print(f"\n✅ SUCCESS: Transcript fetched via YouTube API\n")
            return result

        # Step 3: Fallback to Whisper transcription
        print("\n🎵 YouTube transcript not available. Using Whisper fallback...\n")

        # Download audio
        audio_path = download_audio_from_youtube(youtube_url)
        if not audio_path:
            result["error"] = "Failed to download audio"
            return result

        # Transcribe with Whisper
        transcript = generate_transcript_from_audio(audio_path)
        if not transcript:
            result["error"] = "Failed to transcribe audio"
            return result

        result["transcript"] = transcript
        result["method_used"] = "whisper"
        print(f"\n✅ SUCCESS: Transcript generated via Whisper\n")

        return result

    except Exception as e:
        result["error"] = f"Unexpected error: {str(e)}"
        print(f"\n❌ FAILED: {result['error']}\n")
        return result

    finally:
        # Always clean up temporary audio file
        if audio_path:
            cleanup_audio_file(audio_path)


# ============================================================================
# STEP 5: INTEGRATION FUNCTION (Use this with your summarizer)
# ============================================================================

def process_youtube_video(youtube_url: str, summarizer_function) -> Dict:
    """
    Complete pipeline: Extract transcript + Generate summary.
    This is your integration point with existing summarizer.

    Args:
        youtube_url: YouTube video URL
        summarizer_function: Your existing summarizer function(transcript) -> summary

    Returns:
        Dictionary with transcript, summary, and metadata
    """
    # Get transcript using master function
    transcript_result = fetch_final_transcript(youtube_url)

    if transcript_result["error"]:
        return {
            "success": False,
            "error": transcript_result["error"],
            "transcript": None,
            "summary": None,
            "method_used": None
        }

    # Pass transcript to your existing summarizer
    summary = summarizer_function(transcript_result["transcript"])

    return {
        "success": True,
        "transcript": transcript_result["transcript"],
        "summary": summary,
        "method_used": transcript_result["method_used"],
        "video_id": transcript_result["video_id"],
        "error": None
    }


# ============================================================================
# STEP 6: TEST EXAMPLES
# ============================================================================

def test_system():
    """Run test cases to verify the system works."""
    print("🧪 TESTING YOUTUBE TRANSCRIPT SYSTEM\n")

    # Test with a video that HAS captions (should use YouTube API)
    print("TEST 1: Video with captions")
    test_url_with_captions = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
    result1 = fetch_final_transcript(test_url_with_captions)

    if result1["error"]:
        print(f"❌ Test 1 Failed: {result1['error']}\n")
    else:
        print(f"✅ Test 1 Passed!")
        print(f"   Method: {result1['method_used']}")
        print(f"   Transcript preview: {result1['transcript'][:150]}...\n")

    # Test with a video WITHOUT captions (will use Whisper)
    # Replace with actual video URL without captions if you want to test Whisper
    print("\nℹ️  To test Whisper fallback, use a YouTube URL without captions")


# ============================================================================
# STEP 7: USAGE INSTRUCTIONS
# ============================================================================

"""
HOW TO USE IN GOOGLE COLAB:
============================

CELL 1 - Install dependencies:
-------------------------------
!pip install -q youtube-transcript-api yt-dlp openai-whisper
!apt-get install -y ffmpeg > /dev/null 2>&1

# Enable GPU (IMPORTANT for faster transcription):
# Go to: Runtime > Change runtime type > Hardware accelerator > GPU


CELL 2 - Copy all the code above (from imports to test_system)
-------------------------------
[Paste entire code here]


CELL 3 - Test the system:
-------------------------------
# Simple test
test_system()


CELL 4 - Use with a specific video:
-------------------------------
# Example 1: Just get transcript
youtube_url = "https://www.youtube.com/watch?v=YOUR_VIDEO_ID"
result = fetch_final_transcript(youtube_url)

if result["error"]:
    print(f"Error: {result['error']}")
else:
    print(f"Method used: {result['method_used']}")
    print(f"Transcript length: {len(result['transcript'])} characters")
    print(f"Preview: {result['transcript'][:500]}...")


CELL 5 - Integration with your summarizer:
-------------------------------
# Define your existing summarizer function
def my_summarizer(transcript):
    # Your existing summarization logic here
    summary = f"Summary of {len(transcript)} characters transcript"
    return summary

# Use complete pipeline
final_result = process_youtube_video(youtube_url, my_summarizer)

if final_result["success"]:
    print(f"✅ Success!")
    print(f"Method: {final_result['method_used']}")
    print(f"Transcript length: {len(final_result['transcript'])}")
    print(f"Summary: {final_result['summary']}")
else:
    print(f"❌ Error: {final_result['error']}")


TIPS:
-----
1. Always enable GPU in Colab for faster Whisper transcription
2. Start with 'tiny' or 'base' model for testing (faster)
3. Use 'small' or 'medium' for better accuracy in production
4. First test with videos that have captions (faster, uses YouTube API)
5. Then test with videos without captions (slower, uses Whisper)
"""

print("✅ YouTube Transcript System loaded successfully!")
print("📝 Run test_system() to verify everything works")
print("🚀 Or use fetch_final_transcript(url) directly")

test_system()

# Test with any YouTube URL
youtube_url = "https://youtu.be/LbkO84MsmyM?si=ijwQcozdP77voAKN"
result = fetch_final_transcript(youtube_url)

if result["error"]:
    print(f"Error: {result['error']}")
else:
    print(f"✅ Method used: {result['method_used']}")
    print(f"📊 Transcript length: {len(result['transcript'])} characters")
    print(f"📝 Preview:\n{result['transcript'][:]}...")

